const ADD_CATEGORY = 'ADD_CATEGORY';
const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
const GET_CATEGORY = 'GET_CATEGORY';
const GET_CATEGORIES = 'GET_CATEGORIES';
const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
const PUT_CATEGORY = 'PUT_CATEGORY';
const DELETE_CATEGORY = 'DELETE_CATEGORY';

export {ADD_CATEGORY,GET_CATEGORY,GET_CATEGORIES,PUT_CATEGORY,DELETE_CATEGORY,ADD_CATEGORY_SUCCESS,GET_CATEGORIES_SUCCESS};
